FROM ruby:4.0.2-alpine

RUN apk add build-base git
WORKDIR /app
COPY Gemfile Gemfile.lock ./
RUN bundle install
COPY . .

EXPOSE 3000
CMD ["/usr/local/bin/bundle", "exec", "rackup", "--host=0.0.0.0", "--port=3000"]
