name: On push

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: docker compose up -d --build
    - run: sleep 3
    - run: docker compose exec -T web curl -f -LI http://localhost:3000
    - run: docker compose down

  deploy_production:
    needs: test
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: zenato/docker-action@master
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        repository: ${{ secrets.REGISTRY_REPO }}
        registry: ${{ secrets.REGISTRY_URL }}
        tag: production
